const courseData = {
  "Técnico em Administração": { type:"Curso Técnico", hours:"Mínimo de 800 horas — referência geral SEED-PR", study:"Rotinas administrativas, protocolos e arquivos, documentos, controle de estoques, fundamentos de gestão e uso de sistemas de informação gerencial.", jobs:"Áreas administrativas, apoio à gestão, atendimento, compras, materiais, estoque e rotinas organizacionais.", subjects:["Processos administrativos","Gestão de pessoas","Gestão de materiais","Documentação e arquivos","Sistemas de informação","Fundamentos de gestão"] },
  "Técnico em Recursos Humanos": { type:"Curso Técnico", hours:"Mínimo de 800 horas — referência geral SEED-PR", study:"Rotinas de departamento pessoal, recrutamento e seleção, integração, treinamento, desenvolvimento, avaliação de desempenho, cargos, salários, benefícios, férias e rescisão.", jobs:"Departamento pessoal, recrutamento e seleção, treinamento e desenvolvimento, apoio de RH e rotinas trabalhistas.", subjects:["Recrutamento e seleção","Departamento pessoal","Treinamento e desenvolvimento","Cargos e salários","Benefícios","Legislação trabalhista"] },
  "Técnico em Logística": { type:"Curso Técnico", hours:"Mínimo de 800 horas — referência geral SEED-PR", study:"Transporte, armazenagem, compras, recebimento, movimentação, expedição, distribuição, manutenção e gestão de estoques.", jobs:"Almoxarifado, estoque, compras, transporte, expedição, distribuição e operações logísticas.", subjects:["Gestão de estoques","Armazenagem","Transportes","Compras","Expedição","Distribuição"] },
  "Técnico em Desenvolvimento de Sistemas": { type:"Curso Técnico", hours:"Mínimo de 800 horas — referência geral SEED-PR", study:"Programação, manutenção de sistemas, modelagem e consultas em bancos de dados, documentação, qualidade e segurança da informação.", jobs:"Desenvolvimento de software, aplicações web, banco de dados, manutenção de sistemas e suporte em tecnologia.", subjects:["Lógica de programação","Programação","Banco de dados","Desenvolvimento web","Engenharia de software","Segurança e qualidade"] },
  "Técnico em Informática": { type:"Curso Técnico", hours:"Mínimo de 800 horas — referência geral SEED-PR", study:"Fundamentos de informática, hardware, software, sistemas operacionais, redes, internet, manutenção e segurança da informação.", jobs:"Suporte técnico, manutenção, redes, infraestrutura, help desk e áreas de tecnologia.", subjects:["Hardware","Software","Redes","Sistemas operacionais","Manutenção","Segurança da informação"] },
  "Técnico em Contabilidade": { type:"Curso Técnico", hours:"Mínimo de 800 horas — referência geral SEED-PR", study:"Fundamentos contábeis, registros, documentos, rotinas fiscais e administrativas e organização das informações patrimoniais e financeiras.", jobs:"Escritórios contábeis, departamentos fiscais e financeiros, apoio contábil e rotinas administrativas.", subjects:["Fundamentos de contabilidade","Escrituração","Rotinas fiscais","Patrimônio","Finanças","Documentação"] },
  "Técnico em Marketing": { type:"Curso Técnico", hours:"Mínimo de 800 horas — referência geral SEED-PR", study:"Fundamentos de marketing, comportamento do consumidor, planejamento, comunicação, vendas, promoção e estratégias para produtos e serviços.", jobs:"Marketing, atendimento, comunicação, vendas, promoção, mídias e apoio comercial.", subjects:["Fundamentos de marketing","Comportamento do consumidor","Comunicação","Vendas","Planejamento","Marketing digital"] },
  "Técnico em Segurança do Trabalho": { type:"Curso Técnico", hours:"Mínimo de 800 horas — referência geral SEED-PR", study:"Prevenção de acidentes, identificação, avaliação e controle de riscos, normas de segurança, higiene e saúde do trabalho, ações educativas e orientação sobre EPI.", jobs:"Segurança do trabalho em indústrias, comércio, serviços, construção e organizações com ações de prevenção.", subjects:["Prevenção de riscos","Segurança ocupacional","Higiene do trabalho","Ergonomia","Legislação e normas","EPI e ações educativas"] },
  "Técnico em Serviços Jurídicos": { type:"Curso Técnico", hours:"Mínimo de 800 horas — referência geral SEED-PR", study:"Apoio a rotinas administrativas e documentais relacionadas ao ambiente jurídico, organização de processos e atendimento.", jobs:"Escritórios, departamentos jurídicos, cartórios e apoio administrativo em atividades jurídicas.", subjects:["Documentação","Organização de processos","Rotinas jurídicas","Atendimento","Noções de legislação","Ética"] },
  "Técnico em Edificações": { type:"Curso Técnico", hours:"Mínimo de 800 horas — referência geral SEED-PR", study:"Leitura e interpretação de projetos, desenho técnico, materiais, processos construtivos, instalações, orçamento e acompanhamento de obras.", jobs:"Construtoras, escritórios, obras, orçamento, projetos, acompanhamento e apoio técnico.", subjects:["Desenho técnico","Materiais de construção","Tecnologia da construção","Instalações prediais","Orçamentos","Topografia"] },
  "Técnico em Qualidade": { type:"Curso Técnico", hours:"Mínimo de 800 horas — referência geral SEED-PR", study:"Gestão da qualidade, padronização de processos, indicadores, melhoria contínua, documentação e práticas de controle.", jobs:"Qualidade, processos, produção, auditoria interna e apoio à melhoria contínua.", subjects:["Gestão da qualidade","Processos","Indicadores","Padronização","Melhoria contínua","Documentação"] },
  "Informática Básica": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Uso do computador, arquivos e pastas, internet, editores de texto, recursos digitais e noções de segurança.", jobs:"Apoio em rotinas administrativas e uso cotidiano de tecnologia.", subjects:["Computador","Windows","Internet","Editor de texto","Arquivos","Segurança digital"] },
  "Excel": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Planilhas, fórmulas, funções, organização de dados, gráficos e recursos para controle e análise.", jobs:"Rotinas administrativas, financeiras, comerciais, estoque e análise de informações.", subjects:["Planilhas","Fórmulas","Funções","Gráficos","Dados","Relatórios"] },
  "Auxiliar de Educação Infantil": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Rotinas de cuidado, desenvolvimento infantil, organização de atividades, ludicidade, higiene e apoio pedagógico.", jobs:"Apoio em escolas, centros de educação infantil e espaços de atendimento à infância.", subjects:["Desenvolvimento infantil","Cuidados","Ludicidade","Rotinas","Higiene","Apoio pedagógico"] },
  "Educação Especial": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Conceitos de educação inclusiva, acessibilidade, estratégias pedagógicas e apoio às diferenças de aprendizagem.", jobs:"Apoio educacional e atuação complementar em contextos inclusivos, conforme formação e legislação aplicável.", subjects:["Inclusão","Acessibilidade","Estratégias pedagógicas","Desenvolvimento","Tecnologia assistiva","Práticas inclusivas"] },
  "Alfabetização e Letramento": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Processos de alfabetização, práticas de leitura e escrita, consciência fonológica e estratégias pedagógicas.", jobs:"Apoio pedagógico e atividades educacionais relacionadas à alfabetização, conforme habilitação profissional.", subjects:["Alfabetização","Letramento","Leitura","Escrita","Consciência fonológica","Práticas pedagógicas"] },
  "Contação de História": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Técnicas de narração, expressão, seleção de histórias, recursos e estratégias para estimular imaginação e leitura.", jobs:"Projetos educativos, bibliotecas, recreação, atividades culturais e apoio em práticas pedagógicas.", subjects:["Narração","Expressão","Literatura infantil","Recursos","Leitura","Dramatização"] },
  "Recreação e Ludicidade": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Brincadeiras, jogos, atividades recreativas, ludicidade e planejamento de experiências para diferentes públicos.", jobs:"Escolas, recreação, projetos educativos, eventos e espaços de atendimento infantil.", subjects:["Jogos","Brincadeiras","Ludicidade","Planejamento","Recreação","Dinâmicas"] },
  "Práticas Pedagógicas": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Planejamento, organização de atividades, avaliação, metodologias e estratégias para contextos educacionais.", jobs:"Apoio e desenvolvimento de práticas educacionais, conforme formação e função exercida.", subjects:["Planejamento","Metodologias","Avaliação","Atividades","Gestão de sala","Práticas educativas"] },
  "Neuroeducação": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Relações entre aprendizagem, desenvolvimento, atenção, memória, emoções e estratégias educacionais.", jobs:"Apoio a práticas educacionais e desenvolvimento de estratégias de aprendizagem, conforme habilitação profissional.", subjects:["Aprendizagem","Memória","Atenção","Emoções","Desenvolvimento","Estratégias"] },
  "Cuidador de Idosos": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Rotinas de cuidado, higiene, alimentação, segurança, mobilidade e apoio à autonomia da pessoa idosa.", jobs:"Atendimento domiciliar, instituições de longa permanência e serviços de apoio, conforme requisitos locais.", subjects:["Cuidados básicos","Higiene","Alimentação","Mobilidade","Segurança","Apoio à autonomia"] },
  "Oratória": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Comunicação oral, organização de ideias, postura, voz, apresentação e técnicas para falar em público.", jobs:"Apresentações profissionais, atendimento, vendas, treinamentos e comunicação no trabalho.", subjects:["Comunicação","Voz","Postura","Apresentação","Argumentação","Expressão"] },
  "Cuidador Infantil": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Cuidados, segurança, rotinas, higiene, alimentação e atividades adequadas ao desenvolvimento infantil.", jobs:"Residências, espaços de cuidado infantil e serviços de apoio à infância, conforme requisitos locais.", subjects:["Rotinas","Higiene","Alimentação","Segurança","Brincadeiras","Desenvolvimento"] },
  "Desenvolvimento Infantil": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Aspectos do desenvolvimento físico, cognitivo, emocional, social e da aprendizagem na infância.", jobs:"Apoio a práticas educacionais e de cuidado infantil, conforme formação e função.", subjects:["Desenvolvimento físico","Cognitivo","Emocional","Social","Aprendizagem","Brincar"] },
  "Relações Humanas": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Comunicação interpessoal, convivência, empatia, trabalho em equipe e resolução de conflitos.", jobs:"Aplicação em equipes, atendimento, liderança e ambientes organizacionais.", subjects:["Comunicação","Empatia","Equipe","Conflitos","Convivência","Liderança"] },
  "Departamento Pessoal": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Rotinas de admissão, registros, folha, benefícios, férias, afastamentos e desligamentos.", jobs:"Apoio em departamento pessoal e rotinas administrativas de pessoal.", subjects:["Admissão","Folha","Benefícios","Férias","Afastamentos","Rescisão"] },
  "Técnicas de Vendas": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Abordagem, negociação, atendimento, apresentação de produtos, objeções e pós-venda.", jobs:"Vendas, atendimento, comércio, representação e relacionamento com clientes.", subjects:["Abordagem","Atendimento","Negociação","Objeções","Fechamento","Pós-venda"] },
  "Gestão Empresarial": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Noções de planejamento, organização, pessoas, processos, finanças e tomada de decisão.", jobs:"Apoio administrativo, gestão de processos e desenvolvimento de negócios.", subjects:["Planejamento","Processos","Pessoas","Finanças","Indicadores","Decisão"] },
  "Saúde e Qualidade": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Conceitos de qualidade de vida, prevenção, hábitos saudáveis e organização de práticas de cuidado.", jobs:"Ações educativas e apoio a programas de promoção de saúde, conforme formação.", subjects:["Prevenção","Hábitos saudáveis","Qualidade de vida","Bem-estar","Educação em saúde"] },
  "Monitor Infantil": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Acompanhamento de crianças, organização de atividades, segurança, rotina e apoio ao desenvolvimento.", jobs:"Escolas, projetos, espaços de recreação e serviços de apoio infantil, conforme requisitos.", subjects:["Rotinas","Segurança","Atividades","Brincadeiras","Desenvolvimento"] },
  "Literatura Infantil": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Gêneros, obras, leitura, mediação e estratégias para aproximar crianças da literatura.", jobs:"Bibliotecas, projetos de leitura, escolas e atividades culturais, conforme formação.", subjects:["Gêneros","Leitura","Mediação","Autores","Projetos de leitura"] },
  "Ética Profissional": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Princípios éticos, responsabilidade, conduta profissional, relações de trabalho e tomada de decisão responsável.", jobs:"Aplicável a diferentes ambientes profissionais.", subjects:["Ética","Responsabilidade","Conduta","Relacionamento","Decisão"] },
  "Saúde Mental no Ambiente de Trabalho": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Bem-estar, relações de trabalho, fatores psicossociais, prevenção e práticas de cuidado no ambiente organizacional.", jobs:"Apoio a ações educativas e de promoção de bem-estar, conforme formação.", subjects:["Bem-estar","Fatores psicossociais","Prevenção","Comunicação","Cuidado"] },
  "Cuidador de Pessoas com Deficiência": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Cuidados, apoio à autonomia, segurança, comunicação e rotina de pessoas com deficiência.", jobs:"Serviços de cuidado e apoio, conforme requisitos e limites de atuação profissional.", subjects:["Autonomia","Cuidados","Comunicação","Segurança","Rotinas"] },
  "Sustentabilidade": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Consumo consciente, gestão de recursos, práticas sustentáveis e responsabilidade socioambiental.", jobs:"Ações e projetos ambientais em organizações e comunidades.", subjects:["Sustentabilidade","Recursos","Consumo","Resíduos","Responsabilidade"] },
  "Educação Ambiental": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Conceitos ambientais, preservação, cidadania, projetos e práticas educativas.", jobs:"Projetos educativos, ações comunitárias e ambientais, conforme formação.", subjects:["Meio ambiente","Preservação","Cidadania","Projetos","Educação"] },
  "Maquiagem": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Preparação da pele, técnicas de maquiagem, produtos, ferramentas e cuidados de higiene.", jobs:"Atendimento em maquiagem e beleza, conforme qualificação e regras locais.", subjects:["Preparação da pele","Produtos","Técnicas","Higiene","Finalização"] },
  "Cuidados com a Pele": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Higiene, rotina de cuidados, tipos de pele, produtos e hábitos de prevenção e proteção.", jobs:"Serviços e orientação estética dentro dos limites da formação e legislação aplicável.", subjects:["Tipos de pele","Higiene","Produtos","Rotina","Proteção"] },
  "Manicure e Pedicure": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Higiene, preparação, corte, esmaltação e cuidados básicos com unhas e mãos/pés.", jobs:"Atendimento em salões, espaços de beleza e trabalho autônomo, conforme regras locais.", subjects:["Higiene","Preparação","Esmaltação","Materiais","Atendimento"] },
  "Robótica Educacional": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Lógica, montagem, sensores, programação e projetos para aprendizagem baseada em tecnologia.", jobs:"Projetos educacionais, oficinas e apoio a atividades de tecnologia.", subjects:["Lógica","Montagem","Sensores","Programação","Projetos"] },
  "ChatGPT para o Mercado de Trabalho": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Uso responsável de ferramentas de IA para produtividade, pesquisa, escrita, organização e apoio a tarefas profissionais.", jobs:"Aplicação transversal em áreas administrativas, comerciais, educacionais e de serviços.", subjects:["Prompts","Produtividade","Texto","Pesquisa","Organização","Uso responsável de IA"] },
  "Pensamento Computacional": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Decomposição de problemas, padrões, algoritmos, lógica e resolução estruturada de desafios.", jobs:"Competência aplicada a tecnologia, educação, gestão e resolução de problemas.", subjects:["Algoritmos","Lógica","Padrões","Decomposição","Resolução de problemas"] },
  "Beleza": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Noções de atendimento, higiene, organização e técnicas introdutórias relacionadas à área da beleza.", jobs:"Apoio e serviços de beleza conforme a formação realizada e regras locais.", subjects:["Higiene","Atendimento","Organização","Técnicas de beleza"] },
  "Agronegócio": { type:"Curso Livre", hours:"Definida no plano do curso do Instituto", study:"Noções de cadeia produtiva, gestão, comercialização, produção e organização do agronegócio.", jobs:"Apoio administrativo e operacional em atividades ligadas ao agronegócio.", subjects:["Cadeia produtiva","Gestão","Produção","Comercialização","Mercado"] },
  "Magistério": { type:"Formação para Magistério", hours:"A definir conforme a organização curricular e habilitação vigente do curso", study:"Formação pedagógica, fundamentos da educação, desenvolvimento e práticas de ensino voltadas à docência.", jobs:"Atuação docente conforme habilitação, legislação e requisitos da rede ou instituição contratante.", subjects:["Fundamentos da educação","Didática","Desenvolvimento","Alfabetização","Práticas pedagógicas","Avaliação"] }
};

const style = document.createElement('style');
style.textContent = `
.course-item{cursor:pointer;position:relative;transition:.18s}.course-item:hover{transform:translateY(-2px);box-shadow:0 10px 24px #4f1d7814;border-color:#d6c4e5}.course-item::after{content:'Ver detalhes →';float:right;color:var(--orange);font-size:10px;font-weight:900;margin-left:8px}.course-modal{position:fixed;inset:0;background:#170821b8;display:none;align-items:center;justify-content:center;padding:20px;z-index:9999}.course-modal.open{display:flex}.course-dialog{width:min(940px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:22px;padding:34px;box-shadow:0 30px 90px #0008}.course-header{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}.course-badge{display:inline-block;background:#f5effa;color:#4f1d78;padding:6px 10px;border-radius:999px;font-size:11px;font-weight:900}.course-dialog h2{font-size:32px;line-height:1.15;color:#4f1d78;margin:10px 0 0}.course-close{border:0;background:#f1f2f5;color:#333;width:40px;height:40px;border-radius:10px;font-size:25px;cursor:pointer}.course-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:24px}.course-panel{border:1px solid #e7e9ef;border-radius:15px;padding:20px}.course-panel h3{margin:0 0 9px;color:#4f1d78;font-size:17px}.course-panel p{margin:0;color:#687083;line-height:1.65}.course-hours{font-size:20px;font-weight:900;color:#f57c18;line-height:1.35}.course-subjects{display:flex;flex-wrap:wrap;gap:7px}.course-subject{background:#faf7fc;border:1px solid #ece1f4;padding:7px 9px;border-radius:999px;font-size:11px;color:#4f1d78;font-weight:700}.course-source{margin-top:16px;padding:14px;background:#f8f8fb;border-radius:12px;color:#687083;font-size:12px;line-height:1.55}.course-source strong{color:#232733}@media(max-width:700px){.course-dialog{padding:23px}.course-dialog h2{font-size:27px}.course-grid{grid-template-columns:1fr}.course-item::after{display:block;float:none;margin-top:5px}}
`;
document.head.appendChild(style);

const modal = document.createElement('div');
modal.className = 'course-modal';
modal.innerHTML = `<div class="course-dialog" role="dialog" aria-modal="true" aria-labelledby="course-title"><div class="course-header"><div><div class="course-badge" id="course-category"></div><h2 id="course-title"></h2></div><button class="course-close" type="button" aria-label="Fechar">×</button></div><div class="course-grid"><div class="course-panel"><h3>O que você estuda</h3><p id="course-study"></p></div><div class="course-panel"><h3>Possibilidades de atuação</h3><p id="course-jobs"></p></div><div class="course-panel"><h3>Carga horária</h3><div class="course-hours" id="course-hours"></div></div><div class="course-panel"><h3>Componentes / áreas de estudo</h3><div class="course-subjects" id="course-subjects"></div></div></div><div class="course-source"><strong>Fonte e observação:</strong> para cursos técnicos, a carga horária exibida como referência geral é a indicação de mínimo de 800 horas da SEED-PR. A distribuição de horas por disciplina, porém, deve ser retirada da matriz curricular vigente e específica do curso e da oferta. As descrições não substituem o plano curricular oficial do Instituto.</div></div>`;
document.body.appendChild(modal);

const closeModal = () => { modal.classList.remove('open'); document.body.style.overflow=''; };
modal.querySelector('.course-close').addEventListener('click', closeModal);
modal.addEventListener('click', e => { if(e.target === modal) closeModal(); });
document.addEventListener('keydown', e => { if(e.key === 'Escape') closeModal(); });

document.querySelectorAll('.course-item').forEach(item => {
  item.setAttribute('role','button');
  item.setAttribute('tabindex','0');
  const name = item.textContent.replace(/^(\d+\.)\s*/,'').trim();
  const open = () => {
    const d = courseData[name] || { type:'Formação', hours:'Informação em validação', study:'Detalhes do conteúdo serão publicados conforme o plano do curso.', jobs:'As possibilidades de atuação dependem da formação e dos requisitos profissionais aplicáveis.', subjects:['Informação em validação'] };
    document.getElementById('course-category').textContent = d.type;
    document.getElementById('course-title').textContent = name;
    document.getElementById('course-study').textContent = d.study;
    document.getElementById('course-jobs').textContent = d.jobs;
    document.getElementById('course-hours').textContent = d.hours;
    document.getElementById('course-subjects').innerHTML = d.subjects.map(s => `<span class="course-subject">${s}</span>`).join('');
    modal.classList.add('open');
    document.body.style.overflow='hidden';
  };
  item.addEventListener('click', open);
  item.addEventListener('keydown', e => { if(e.key === 'Enter' || e.key === ' ') { e.preventDefault(); open(); } });
});
