export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const host = url.hostname.toLowerCase();
    const json = (data, status = 200, extra = {}) => Response.json(data, { status, headers: { 'Cache-Control':'no-store, max-age=0', ...extra } });
    const security = (response) => { const h = new Headers(response.headers); h.set('X-Content-Type-Options','nosniff'); h.set('X-Frame-Options','SAMEORIGIN'); h.set('Referrer-Policy','strict-origin-when-cross-origin'); h.set('Permissions-Policy','camera=(), microphone=(), geolocation=()'); h.set('Cross-Origin-Opener-Policy','same-origin'); h.set('Cross-Origin-Resource-Policy','same-origin'); return new Response(response.body,{status:response.status,statusText:response.statusText,headers:h}); };
    const readJson = async()=>{try{return await request.json()}catch(_){return{}}};
    const hex = buf => [...new Uint8Array(buf)].map(b=>b.toString(16).padStart(2,'0')).join('');
    const bytes = hexstr => Uint8Array.from(hexstr.match(/.{1,2}/g)||[],x=>parseInt(x,16));
    const sha256 = async text => hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)));
    const randomToken = () => { const a=new Uint8Array(32); crypto.getRandomValues(a); return hex(a); };
    const passwordHash = async password => { const a=new Uint8Array(16);crypto.getRandomValues(a);const salt=hex(a);const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:bytes(salt),iterations:120000,hash:'SHA-256'},key,256);return `pbkdf2$120000$${salt}$${hex(bits)}`; };
    const passwordVerify = async(password,stored)=>{const p=String(stored||'').split('$');if(p.length!==4||p[0]!=='pbkdf2')return false;const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:bytes(p[2]),iterations:Number(p[1]),hash:'SHA-256'},key,256);return hex(bits)===p[3];};
    const setSessionCookie=(token,maxAge)=>`__Host-iecg=${token}; Max-Age=${maxAge}; Path=/; HttpOnly; Secure; SameSite=Lax`;
    const sessionToken=request.headers.get('Cookie')?.match(/(?:^|;\s*)__Host-iecg=([^;]+)/)?.[1]||null;
    const authUser=async()=>{if(!env.DB||!sessionToken)return null;const th=await sha256(sessionToken);return await env.DB.prepare('SELECT u.id,u.full_name,u.username,u.email,u.role,u.active FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? AND u.active=1').bind(th,new Date().toISOString()).first()};
    const audit=async(user,action,entity,id,details)=>{try{await env.DB.prepare('INSERT INTO audit_logs (user_id,action,entity,entity_id,details) VALUES (?,?,?,?,?)').bind(user?.id||null,action,entity,id||null,details||null).run()}catch(_){}};
    const requireAuth=async(admin=false)=>{const u=await authUser();if(!u)return [null,json({error:'Não autenticado.'},401)];if(admin&&u.role!=='administrador')return [null,json({error:'Acesso exclusivo do administrador.'},403)];return [u,null]};
    const list=async(table)=>{const allowed=['students','teachers','employees','courses'];if(!allowed.includes(table))throw new Error('Tabela inválida');return (await env.DB.prepare(`SELECT * FROM ${table} ORDER BY id DESC LIMIT 500`).all()).results};
    const createSimple=async(table,b)=>{const specs={students:['full_name','cpf','birth_date','email','phone','address','status','notes'],teachers:['full_name','cpf','email','phone','professional_registration','status','notes'],employees:['full_name','cpf','birth_date','email','phone','address','job_title','hire_date','salary','payment_method','status','notes'],courses:['name','description','duration','modality','status']};const cols=specs[table];const vals=cols.map(c=>b[c]??(c==='status'?'ativo':null));const r=await env.DB.prepare(`INSERT INTO ${table} (${cols.join(',')}) VALUES (${cols.map(()=>'?').join(',')})`).bind(...vals).run();return r.meta.last_row_id};
    const api=async()=>{
      if(!env.DB)return json({error:'Banco D1 não configurado no Worker.'},500);
      const p=url.pathname,m=request.method;
      if(p==='/api/health'&&m==='GET'){try{const r=await env.DB.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all();return json({ok:true,database:'connected',tables:r.results.map(x=>x.name),timestamp:new Date().toISOString()})}catch(e){return json({ok:false,error:e.message},500)}}
      if(p==='/api/auth/setup'&&m==='POST'){const b=await readJson();const n=await env.DB.prepare('SELECT COUNT(*) total FROM users').first();if(Number(n?.total)>0)return json({error:'A configuração inicial já foi concluída.'},409);if(!b.full_name||!b.username||!b.password)return json({error:'Preencha nome, usuário e senha.'},400);if(b.password!==b.password_confirmation)return json({error:'As senhas não coincidem.'},400);if(String(b.password).length<8)return json({error:'Use uma senha com pelo menos 8 caracteres.'},400);const username=String(b.username).trim().toLowerCase();const ph=await passwordHash(b.password);const r=await env.DB.prepare('INSERT INTO users (full_name,username,password_hash,role,active) VALUES (?,?,?,?,1)').bind(String(b.full_name).trim(),username,ph,'administrador').run();await audit({id:r.meta.last_row_id},'create','users',r.meta.last_row_id,'Primeiro administrador');return json({ok:true},201)}
      if(p==='/api/auth/login'&&m==='POST'){const b=await readJson();const login=String(b.login||'').trim().toLowerCase();const u=await env.DB.prepare('SELECT * FROM users WHERE lower(username)=? OR lower(email)=? LIMIT 1').bind(login,login).first();if(!u||!u.active||!(await passwordVerify(String(b.password||''),u.password_hash)))return json({error:'Usuário ou senha inválidos.'},401);const token=randomToken(),th=await sha256(token),exp=new Date(Date.now()+8*60*60*1000).toISOString();await env.DB.prepare('INSERT INTO sessions (user_id,token_hash,expires_at,last_seen_at) VALUES (?,?,?,?,?)').bind(u.id,th,exp,new Date().toISOString()).run();await audit(u,'login','users',u.id,'Login');return json({ok:true,user:{id:u.id,full_name:u.full_name,username:u.username,email:u.email,role:u.role}},200,{'Set-Cookie':setSessionCookie(token,8*60*60)})}
      if(p==='/api/auth/logout'&&m==='POST'){const u=await authUser();if(sessionToken)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha256(sessionToken)).run();if(u)await audit(u,'logout','users',u.id,'Logout');return json({ok:true},200,{'Set-Cookie':setSessionCookie('',0)})}
      if(p==='/api/auth/me'&&m==='GET'){const u=await authUser();return u?json({user:u}):json({user:null},401)}
      const [user,authErr]=await requireAuth();if(authErr)return authErr;
      if(p==='/api/dashboard'&&m==='GET'){const [s,e,f,r]=await Promise.all([env.DB.prepare("SELECT COUNT(*) total FROM students WHERE status='ativo'").first(),env.DB.prepare('SELECT COUNT(*) total FROM enrollments').first(),env.DB.prepare("SELECT COUNT(*) total FROM employees WHERE status!='desligado'").first(),env.DB.prepare("SELECT COALESCE(SUM(final_amount),0) total FROM financial_entries WHERE status!='cancelado'").first()]);return json({counts:{students:Number(s?.total||0),enrollments:Number(e?.total||0),employees:Number(f?.total||0),revenue:Number(r?.total||0)}})}
      if(p==='/api/users'&&m==='GET'){const [u,err]=await requireAuth(true);if(err)return err;const r=await env.DB.prepare('SELECT id,full_name,username,email,role,active,created_at FROM users ORDER BY id DESC').all();return json({results:r.results})}
      if(p==='/api/users'&&m==='POST'){const [u,err]=await requireAuth(true);if(err)return err;const b=await readJson();if(!b.full_name||!b.username||!b.password)return json({error:'Nome, usuário e senha são obrigatórios.'},400);if(String(b.password).length<8)return json({error:'A senha deve ter pelo menos 8 caracteres.'},400);const ph=await passwordHash(b.password);try{const r=await env.DB.prepare('INSERT INTO users (full_name,username,email,password_hash,role,active) VALUES (?,?,?,?,?,1)').bind(String(b.full_name).trim(),String(b.username).trim().toLowerCase(),b.email||null,ph,b.role||'aluno').run();await audit(u,'create','users',r.meta.last_row_id,'Usuário');return json({ok:true,id:r.meta.last_row_id},201)}catch(e){return json({error:'Não foi possível criar o usuário. Verifique duplicidade de usuário/e-mail.'},409)}}
      const userPatch=p.match(/^\/api\/users\/(\d+)$/);if(userPatch&&m==='PATCH'){const [u,err]=await requireAuth(true);if(err)return err;const b=await readJson();if(Number(userPatch[1])===u.id&&Number(b.active)===0)return json({error:'Não é possível desativar sua própria conta.'},400);await env.DB.prepare('UPDATE users SET active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(Number(b.active)?1:0,Number(userPatch[1])).run();await audit(u,'update','users',Number(userPatch[1]),'Status alterado');return json({ok:true})}
      if(p==='/api/students'&&m==='GET')return json({results:await list('students')});
      if(p==='/api/teachers'&&m==='GET')return json({results:await list('teachers')});
      if(p==='/api/employees'&&m==='GET')return json({results:await list('employees')});
      if(p==='/api/courses'&&m==='GET')return json({results:await list('courses')});
      const simplePost={students:'Alunos',teachers:'Professores',employees:'Funcionários',courses:'Cursos'};for(const table of Object.keys(simplePost)){if(p===`/api/${table}`&&m==='POST'){const [u,err]=await requireAuth(true);if(err)return err;const b=await readJson();const required=table==='courses'?b.name:b.full_name;if(!required)return json({error:'Campo obrigatório não informado.'},400);try{const id=await createSimple(table,b);await audit(u,'create',table,id,simplePost[table]);return json({ok:true,id},201)}catch(e){return json({error:'Não foi possível salvar. Verifique dados duplicados ou inválidos.'},409)}}}
      if(p==='/api/enrollments'&&m==='GET'){const r=await env.DB.prepare('SELECT e.*,s.full_name student_name,c.name course_name FROM enrollments e JOIN students s ON s.id=e.student_id JOIN courses c ON c.id=e.course_id ORDER BY e.id DESC').all();return json({results:r.results})}
      if(p==='/api/enrollments'&&m==='POST'){const [u,err]=await requireAuth(true);if(err)return err;const b=await readJson();if(!b.student_id||!b.course_id)return json({error:'Aluno e curso são obrigatórios.'},400);try{const r=await env.DB.prepare('INSERT INTO enrollments (student_id,course_id,enrollment_number,start_date,status,notes) VALUES (?,?,?,?,?,?)').bind(Number(b.student_id),Number(b.course_id),b.enrollment_number||null,b.start_date||null,b.status||'ativa',b.notes||null).run();await audit(u,'create','enrollments',r.meta.last_row_id,'Matrícula');return json({ok:true,id:r.meta.last_row_id},201)}catch(e){return json({error:'Não foi possível criar a matrícula.'},409)}}
      if(p==='/api/financial'&&m==='GET'){const r=await env.DB.prepare('SELECT f.*,s.full_name student_name FROM financial_entries f LEFT JOIN students s ON s.id=f.student_id ORDER BY f.id DESC').all();return json({results:r.results})}
      if(p==='/api/financial'&&m==='POST'){const [u,err]=await requireAuth(true);if(err)return err;const b=await readJson();if(!b.description)return json({error:'Descrição é obrigatória.'},400);const amount=Math.max(0,Number(b.amount||0)),discount=Math.max(0,Number(b.discount||0)),final=Math.max(0,amount-discount);const r=await env.DB.prepare('INSERT INTO financial_entries (student_id,enrollment_id,reference,description,due_date,amount,discount,final_amount,paid_amount,paid_at,status,notes) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)').bind(b.student_id||null,b.enrollment_id||null,b.reference||null,String(b.description).trim(),b.due_date||null,amount,discount,final,Number(b.paid_amount||0),b.paid_at||null,b.status||'pendente',b.notes||null).run();await audit(u,'create','financial_entries',r.meta.last_row_id,'Financeiro');return json({ok:true,id:r.meta.last_row_id},201)}
      const del=p.match(/^\/api\/(students|teachers|employees|courses|enrollments|financial)\/(\d+)$/);if(del&&m==='DELETE'){const [u,err]=await requireAuth(true);if(err)return err;const map={students:'students',teachers:'teachers',employees:'employees',courses:'courses',enrollments:'enrollments',financial:'financial_entries'},t=map[del[1]],id=Number(del[2]);if(del[1]==='courses'){const n=await env.DB.prepare('SELECT COUNT(*) total FROM enrollments WHERE course_id=?').bind(id).first();if(Number(n?.total)>0)return json({error:'Não é possível excluir um curso que possui matrículas.'},409)}await env.DB.prepare(`DELETE FROM ${t} WHERE id=?`).bind(id).run();await audit(u,'delete',t,id,'Exclusão');return json({ok:true})}
      return json({error:'Rota da API não encontrada.'},404);
    };
    if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':url.origin,'Access-Control-Allow-Methods':'GET,POST,PUT,PATCH,DELETE,OPTIONS','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Credentials':'true','Access-Control-Max-Age':'86400'}});
    if(url.pathname.startsWith('/api/'))return api();
    const publicHosts=new Set(['institutocanogrande.com.br','www.institutocanogrande.com.br']),adminHosts=new Set(['portal.institutocanogrande.com.br','admin.institutocanogrande.com.br']);
    const inject=async(page,mode)=>{if(!page.ok)return security(page);return security(new HTMLRewriter().on('body',{element(el){el.append(`<script src="/app-polish.js" defer></script>`,{html:true});if(mode==='portal')el.append(`<script src="/portal-dashboard-pro.js" defer></script>`,{html:true});}}).transform(page));};
    if(publicHosts.has(host)){if(['/','/instituto','/site','/home'].includes(url.pathname)){const page=await env.ASSETS.fetch(new Request(new URL('/landing.html',request.url),request));return inject(page,'landing')}if(['/portal','/admin','/login'].includes(url.pathname))return Response.redirect('https://portal.institutocanogrande.com.br/',302)}
    if(adminHosts.has(host)){if(['/','/portal','/admin','/administrativo','/login'].includes(url.pathname)){const page=await env.ASSETS.fetch(new Request(new URL('/index.html',request.url),request));return inject(page,'portal')}if(['/instituto','/site'].includes(url.pathname))return Response.redirect('https://institutocanogrande.com.br/',302)}
    if(url.pathname==='/index.html')return Response.redirect(new URL('/portal',url),301);if(url.pathname==='/landing.html')return Response.redirect(new URL('/instituto',url),301);if(url.pathname==='/')return Response.redirect(new URL('/instituto',url),302);if(url.pathname==='/login')return Response.redirect(new URL('/portal',url),302);if(url.pathname==='/portal'){const page=await env.ASSETS.fetch(new Request(new URL('/index.html',request.url),request));return inject(page,'portal')}if(url.pathname==='/instituto'){const page=await env.ASSETS.fetch(new Request(new URL('/landing.html',request.url),request));return inject(page,'landing')}
    const blocked=['/src/','/database/','/migrations/','/wrangler.jsonc','/.git/'];if(blocked.some(x=>url.pathname===x||url.pathname.startsWith(x)))return new Response('Not Found',{status:404});const asset=await env.ASSETS.fetch(request);return asset.status===404?security(new Response('Página não encontrada.',{status:404,headers:{'Content-Type':'text/plain; charset=utf-8'}})):security(asset);
  }
};
